<?php

define('SC_STATUS','statusCode');

// define mainly status code of RedFox
define('SC_SUCCESS', 200);
define('SC_INTERNAL_SERVER_ERROR',500);
define('SC_NOT_FOUND', 404);
define('SC_FORBIDDEN', 403);
define('SC_CONFLICT', 409);
define('SC_BAD_REQUEST', 400);

define('SC_DOCTRINE',600);
define('SC_DOCTRINE_ENTITY_UPDATE_ERROR', SC_DOCTRINE+1);
define('SC_DOCTRINE_ENTITY_NOT_FOUND', SC_DOCTRINE_ENTITY_UPDATE_ERROR+1);
define('SC_DOCTRINE_ENTITY_PROPERTIE_NOT_FOUND', SC_DOCTRINE_ENTITY_NOT_FOUND+1);
define('SC_DOCTRINE_PB_DURING_PROCESS', SC_DOCTRINE_ENTITY_PROPERTIE_NOT_FOUND+1);
define('SC_DOCTRINE_DUPLICATE_ENTITY', SC_DOCTRINE_PB_DURING_PROCESS+1);
define('SC_DOCTRINE_ENTITY_DELETE_ERROR', SC_DOCTRINE+1);



// define start Status Code for all RedFox modules 
define('SC_COMFOX',800);

define('SC_MAILFOX',900);




define('SC_REDFOX_MAX_VALUE',1000);
